### ISSUE TITLE
No audio on output codec not found 

### ISSUE THREAD

**Issue by Jogsywer1** [miguelqncosta/TotK-Speedometer#1]
you were right, it is creating the _tmp files and below is the output i am getting:

Traceback (most recent call last):File "/Users/jogswyer1/venv-totk-speedometer/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 262, in write_videofilecodec = extensions_dict[ext]['codec'][0]KeyError: 'codec'During handling of the above exception, another exception occurred:Traceback (most recent call last):File "/Users/jogswyer1/Movies/TotK-Speedometer-main/totk-speedometer.py", line 466, in <module>main()File "/Users/jogswyer1/Movies/TotK-Speedometer-main/totk-speedometer.py", line 451, in mainexport_video_with_overlay(f)File "/Users/jogswyer1/Movies/TotK-Speedometer-main/totk-speedometer.py", line 302, in export_video_with_overlayclip_with_audio.write_videofile(output_filename, audio_codec='aac')File "<decorator-gen-55>", line 2, in write_videofileFile "/Users/jogswyer1/venv-totk-speedometer/lib/python3.9/site-packages/moviepy/decorators.py", line 54, in requires_durationreturn f(clip, *a, **k)File "<decorator-gen-54>", line 2, in write_videofileFile "/Users/jogswyer1/venv-totk-speedometer/lib/python3.9/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_defaultreturn f(clip, *new_a, **new_kw)File "<decorator-gen-53>", line 2, in write_videofileFile "/Users/jogswyer1/venv-totk-speedometer/lib/python3.9/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGBreturn f(clip, *a, **k)File "/Users/jogswyer1/venv-totk-speedometer/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 264, in write_videofileraise ValueError("MoviePy couldn't find the codec associated "ValueError: MoviePy couldn't find the codec associated with the filename. Provide the 'codec' parameter in write_videofile.

Edit: if it helps im on a mac and have been doing everything from the terminal, i did do the files for the visual interface but couldnt figure out how to use it

**Comment by miguelqncosta** [comment]
It looks like the problem is with the video codec:
[valueerror-moviepy-couldnt-find-the-codec-associated-with-the-filename-provid](https://stackoverflow.com/questions/49813130/valueerror-moviepy-couldnt-find-the-codec-associated-with-the-filename-provid)

I made a commit to fix that (hopefully) https://github.com/miguelqncosta/TotK-Speedometer/commit/66f506eb66c88291d1d710c2b41e7e4192fbedf0 

It is already included in the new release. Let me know if that fixed the issue for you.

**Comment by Jogsywer1** [comment]
So excuse my ignorance but how would I go about updating?

**Comment by miguelqncosta** [comment]
I know you already got it working but just in case someone sees this and has the same question, to update you only need to download the zip from the latest [release](https://github.com/miguelqncosta/TotK-Speedometer/releases). Cheers

**Comment by Jogsywer1** [comment]
Yes! And if it helps I didn't replace the file, I copied the contents of the update and then pasted them into the previous folder and just said to replace anything that was already there, not sure if it matters but figured just in case there was data in there from before that I needed, thanks again for your help!
